#cloud-config

# Example cloud init userdata script that sets a machine to a certain well known state.

## Create "devops" user with sudo privileges and SSH key access
users:
  - name: devops
    gecos: Devops User
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    passwd: "{{ 'REPLACE_DEVOPS_PASSWORD_HERE' | password_hash('sha512') }}"
    groups: sudo
    lock_passwd: false
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzXXXXX...XXXXGls7 devops@allhosts

runcmd:
  - mkdir -p /home/devops/.ssh
  - chown -R devops:devops /home/devops/.ssh
  - chmod 0700 /home/devops/.ssh
  - chmod 0600 /home/devops/.ssh/authorized_keys

## Get builduser SSH key for cloning infra baseline
write_files:
  - path: /root/.ssh/builduser
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAv2sPNEAhEljA1KlGjfJz1b96A+a22Xfpa9Q98nWtE74LtYH8

      REDACTED! REPLACE THIS WITH THE ACTUAL VALUE BEFORE RUNNING!

      1Bwg3GRwRyM1jlwyrOrqgfbwmLBS4EnuLA+VuVSn6G5ujT8RAYUj2Q==
      -----END RSA PRIVATE KEY-----
    permissions: '0600'
  - path: /home/kcaps//.ssh/config
    content: |
      Host github.com
          IdentityFile = /home/kcaps/.ssh/id_rsa
          HostkeyAlgorithms +ssh-rsa
          PubkeyAcceptedAlgorithms +ssh-rsa
          StrictHostKeyChecking no
    permissions: '0600'
  - path: /home/kcaps/vault-pass
    content: |
      REPLACE_DEVOPS_PASSWORD_HERE
    permissions: '0600'
  - path: /root/inventory.yaml
    content: |
      ---
      all:
        vars:
        children:
          ubuntu:
            vars:
              ansible_user: root
              ansible_python_interpreter: "/usr/bin/python3"
            children:
              baseline:
                hosts:
                  baseline:
                    ansible_host: localhost
                    ansible_connection: local
    permissions: '0644'
  - path: /root/cloud-init-final.sh
    content: |
      #!/bin/bash

      ## Setup custom certificates & disable SSL verification for APT
      echo 'Acquire { https::Verify-Peer false }' > /etc/apt/apt.conf.d/99verify-peer.conf
      chmod 0644 /etc/apt/apt.conf.d/99verify-peer.conf
      mkdir -p /usr/local/share/ca-certificates
      wget --no-check-certificate -O /usr/local/share/ca-certificates/nso-casub21.crt https://artifactory.company.com/artifactory/generic-local/ca-certificates/our-casub.crt
      apt update
      apt install -y ca-certificates
      update-ca-certificates

      # Clone, adapt, and run Infra baseline on localhost
      GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
      git clone ssh://git@github.nsogroup.com/k-caps/scripts.git /home/kcaps/maas/scripts
      mv /home/kcaps/maas/inventory.yaml /home/kcaps/maas/scripts/inventory.yaml
      mv /home/kcaps/maas/vault-pass /home/kcaps/maas/scripts/vault-pass

      apt install -y ansible
      cd /home/kcaps/maas/scripts/
      ansible-playbook /home/kcaps/maas/scripts/playbooks/deploy_baseline.yml -i /home/kcaps/maas/scripts/inventory.yaml -b --vault-pass-file /home/kcaps/maas/scripts/vault-pass
      apt remove -y ansible
      rm -rf /home/kcaps/maas/scripts/
      rm -f /etc/apt/apt.conf.d/99verify-peer.conf
    permissions: '0744'

runcmd:
  - bash /root/cloud-init-final.sh
